# Generated by Django 6.0 on 2025-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(null=True, to='store.product'),
        ),
    ]
