# Generated by Django 6.0 on 2025-12-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(blank=True, null=True, to='store.product'),
        ),
    ]
