# Generated by Django 6.0 on 2025-12-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Products',
            new_name='products',
        ),
    ]
