# Generated by Django 6.0 on 2025-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_products_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
