# Generated by Django 6.0 on 2025-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_orderitem_payment_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
