# Generated by Django 6.0 on 2025-12-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_vehicle_type_deliveryperson_vehicle_type_and_more'),
        ('store', '0017_payment_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.deliveryperson'),
        ),
    ]
