# Generated by Django 6.0 on 2025-12-30 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(help_text='Date of birth')),
                ('phone_number', models.CharField(help_text='normal your phone number.', max_length=15)),
                ('emergency_contact', models.CharField(help_text='contact number for emergency cases.', max_length=20)),
                ('current_lattitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('citizenship', models.FileField(blank=True, help_text='front and back side of the citizenship card in pdf format', null=True, upload_to='delivery_person/citizenship/')),
                ('driving_license', models.FileField(blank=True, help_text='clear scanned image of driving license', null=True, upload_to='delivery_person/driving_licenses/')),
                ('Vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('vehicle_plate_number', models.CharField(max_length=20)),
                ('vehicle_color', models.CharField(blank=True, default='black', help_text='colour of the vehicle', max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
