# Generated by Django 6.0 on 2025-12-30 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='Vehicle_type',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
